cloudBkp_server:cloudBkp_server.cc cloudBackupSer.hpp model.hpp view.hpp
	g++ cloudBkp_server.cc -o cloudBkp_server -std=c++11 -lpthread -lboost_filesystem -lboost_system -lctemplate -I ~/third_part/include -L ~/third_part/lib

.PHONY:clean
clean:
	rm cloudBkp_server
